- name: Include task list in play - SJobs
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{sjobs}}"

- name: Include task list in play - MJobs
  ansible.builtin.include_tasks:
    file: mjob.yml
  loop: "{{mjobs}}"