- name: Copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml

- name: Create a jenkins jobs ansible
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: http://172.31.47.254:8080
    user: admin